package:
  name: enum34
  version: 0.9.23

source:
  fn: enum34-0.9.23.tar.gz
  url: https://pypi.python.org/packages/source/e/enum34/enum34-0.9.23.tar.gz
  md5: cac9d9f00440d03df1d3bf6516d6e878
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - enum34 = enum34:main
    #
    # Would create an entry point called whoosh that calls whoosh.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - enum

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://bitbucket.org/mchaput/whoosh
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
