package:
  name: patsy
  version: 0.2.1

source:
  fn: patsy-0.2.1.tar.gz
  url: https://pypi.python.org/packages/source/p/patsy/patsy-0.2.1.tar.gz
  md5: ea36c846d62231e41df684a827a5fd58
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - patsy:main
    #
    # Would call patsy.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python

    # requirements.
    #
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - six

test:
  # Python imports
  imports:
    - patsy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: https://github.com/pydata/patsy
  license: BSD License

# See
# https://github.com/ContinuumIO/conda/blob/master/conda/builder/README.txt for
# more information about meta.yaml
